### ISSUE TITLE
JOIN

### ISSUE THREAD

**Issue by nijesmik** [nijesmik/ft_irc#9]
# [JOIN message](https://modern.ircdocs.horse/#join-message)

```
     Command: JOIN
  Parameters: <channel>{,<channel>} [<key>{,<key>}]
  Alt Params: 0
```

## Numeric Replies:
- [x] [ERR_NEEDMOREPARAMS](https://modern.ircdocs.horse/#errneedmoreparams-461) (461)
- [x] [ERR_BADCHANNELKEY](https://modern.ircdocs.horse/#errbadchannelkey-475) (475)
- [x] [ERR_CHANNELISFULL](https://modern.ircdocs.horse/#errchannelisfull-471) (471)
- [x] [ERR_INVITEONLYCHAN](https://modern.ircdocs.horse/#errinviteonlychan-473) (473)
- [x] [ERR_BADCHANMASK](https://modern.ircdocs.horse/#errbadchanmask-476) (476)
- [x] [RPL_TOPIC](https://modern.ircdocs.horse/#rpltopic-332) (332)
- [x] [RPL_NAMREPLY](https://modern.ircdocs.horse/#rplnamreply-353) (353)
- [x] [RPL_ENDOFNAMES](https://modern.ircdocs.horse/#rplendofnames-366) (366)

**Comment by seokulee** [comment]
Channel 없으면 바로 만들어 주고 해당 Client가 Host가 될 수 있게 로직을 만들면 `ERR_NOSUCHCHANNEL` 403 번은 필요없을 것 같은데 어떻게 생각하시나요?
